///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardAllTaskModelRequest {
  int? limit;
  int? skip;

  DashboardAllTaskModelRequest({
    this.limit,
    this.skip,
  });
  DashboardAllTaskModelRequest.fromJson(Map<String, dynamic> json) {
    limit = json['limit']?.toInt();
    skip = json['skip']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['limit'] = limit;
    data['skip'] = skip;
    return data;
  }
}
